

apiVersion: v1
kind: PersistentVolume
metadata:
  name: easegateway-pv5
  labels:
    type: easegateway
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/easegateway"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: easegateway-cluster
spec:
  serviceName: easegateway-hs
  selector:
    matchLabels:
      app: easegateway
  replicas: 1
  template:
    metadata:
      labels:
        app: easegateway
    spec:
      containers:
        - name: easegateway
          image: 192.168.50.105:5001/megaease/easegateway:server-sidecar
          ports:
            - containerPort: 2379
              name: client-port
            - containerPort: 2380
              name: peer-port
            - containerPort: 2381
              name: admin-port
          command: ["/bin/sh"]
          args: ["-c", "/opt/easegateway/bin/easegateway-server -f /opt/eg-config/eg-master.yaml --force-new-cluster"]
          volumeMounts:
            - name: easegateway
              mountPath: /opt/eg-data/
            - name: easegateway-cm
              mountPath: /opt/eg-config/eg-master.yaml
              subPath: eg-master.yaml
      volumes:
        - name: easegateway-cm
          configMap:
            name: easegateway-cluster-cm
  volumeClaimTemplates:
    - metadata:
        name: easegateway
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi

