---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      application:
        name:  pet-api-gateway
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: mesh.megaease.com/v1beta1
kind: MeshDeployment
metadata:
  namespace: spring-petclinic
  name: pet-api-gateway
spec:
  service:
    name: pet-api-gateway
  deploy:
    replicas: 1
    selector:
      matchLabels:
        app: pet-api-gateway
    strategy: {}
    template:
      metadata:
        labels:
          app: pet-api-gateway
      spec:
        containers:
        - image: 192.168.50.105:5001/megaease/api-gateway:latest
          name: api-gateway
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 2000m
              memory: 1Gi
          ports:
          - containerPort: 8080
        restartPolicy: Always
status: {}
