---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      application:
        name:  customers-service
      datasource:
        url: jdbc:mysql://km-mysql:3306/meshappdemo?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&verifyServerCertificate=false
        username: meshappdemo
        password: meshappdemo
      jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: mesh.megaease.com/v1beta1
kind: MeshDeployment
metadata:
  namespace: spring-petclinic
  name: customers-service
spec:
  service:
    name: customers-service
  deploy:
    replicas: 1
    selector:
      matchLabels:
        app: customers-service
    template:
      metadata:
        labels:
          app: customers-service
      spec:
        containers:
        - image: 192.168.50.105:5001/megaease/spring-petclinic-customers-service:latest
          name: customers-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          command: ["/bin/sh"]
          args: ["-c", "java -server  -Dspring.profiles.active=sit  -Djava.security.egd=file:/dev/./urandom -jar /application/application.jar"]
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /application/application-sit.yml
            name: configmap-volume-0
            subPath: application-sit.yml
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: application-sit-yml
                  path: application-sit.yml
              name: customers-service
            name: configmap-volume-0
        restartPolicy: Always
status: {}
