apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vets-service
  namespace: spring-petclinic
data:
  application-sit-yml: |
    server:
      port: 8080
    spring:
      application:
        name:  vets-service
      datasource:
        url: jdbc:mysql://km-mysql:3306/service_instance_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&verifyServerCertificate=false
        username: service_instance_db
        password: service_instance_db
        schema: classpath*:db/mysql/schema.sql
        data: classpath*:db/mysql/data.sql
    liquibase:
      enabled: true
      change-log: classpath:/db-changelog/changelog-master.xml
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/
      instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 60

---

apiVersion: mesh.megaease.com/v1beta1
kind: MeshDeployment
metadata:
  namespace: spring-petclinic
  name: vets-service
spec:
  service:
    name: vets-service
  deploy:
    replicas: 1
    selector:
      matchLabels:
        app: vets-service
    template:
      metadata:
        labels:
          app: vets-service
      spec:
        containers:
          - image: springcommunity/spring-petclinic-vets-service:latest
            name: vets-service
            imagePullPolicy: IfNotPresent
            livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/liveness
              initialDelaySeconds: 90
              periodSeconds: 5
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/readiness
              initialDelaySeconds: 15
            lifecycle:
              preStop:
                exec:
                  command: ["sh", "-c", "sleep 10"]
            command: ["/bin/sh"]
            args: ["-c", "java -server  -Dspring.profiles.active=sit  -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 2000m
                memory: 1Gi
            volumeMounts:
              - mountPath: /application-sit.yml
                name: configmap-volume-0
                subPath: application-sit.yml
            ports:
              - containerPort: 8080
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: application-sit-yml
                  path: application-sit.yml
              name: vets-service
            name: configmap-volume-0

        restartPolicy: Always

