
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - mesh.megaease.com
  resources:
  - meshdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.megaease.com
  resources:
  - meshdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - mesh.megaease.com
  resources:
  - meshdeployments/status
  verbs:
  - get
  - patch
  - update
