apiVersion: mesh.megaease.com/v1beta1
kind: MeshDeployment
metadata:
  namespace: test
  name: test-server-v1
spec:
  service:
    name: test-server
    labels:
      canary: internal
  deploy:
    replicas: 2 # tells deployment to run 2 pods matching the template
    selector:
      matchLabels:
        app: test-server-v1
    template:
      metadata:
        labels:
          app: test-server-v1
      spec:
        containers:
        - name: test-server
          image: zhaokundev/easestack-test-server:1.0-alpine
          ports:
          - containerPort: 18080
